CREATE DATABASE TestDb
GO
USE TestDb
GO
CREATE SCHEMA TestSchema
GO
CREATE TABLE TestSchema.TestTable (Id INT NOT NULL,
	Name VARCHAR(20),
	IsSold BIT,
	InvoiceDate DATE)
GO
CREATE USER TestUser WITH PASSWORD='Str0ngP@ssword'
GO
GRANT CONNECT TO TestUser
GO
GRANT SELECT ON TestSchema.TestTable TO TestUser
GO
DROP USER TestUser